"""create components

Revision ID: 0be8422a0593
Revises: 0001_create_boms
Create Date: 2026-08-12 09:55:41.679247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0be8422a0593'
down_revision: Union[str, Sequence[str], None] = '0001_create_boms'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mpn', sa.String(length=150), nullable=False),
    sa.Column('manufacturer', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=150), nullable=True),
    sa.Column('package', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_components_mpn'), 'components', ['mpn'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_components_mpn'), table_name='components')
    op.drop_table('components')
    # ### end Alembic commands ###