"""create alternative records

Revision ID: 0d471b3bcd82
Revises: eb3809484a6f
Create Date: 2026-08-13 10:06:09.312737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d471b3bcd82'
down_revision: Union[str, Sequence[str], None] = 'eb3809484a6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alternative_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_component_id', sa.Integer(), nullable=False),
    sa.Column('alternative_component_id', sa.Integer(), nullable=False),
    sa.Column('compatibility_score', sa.Float(), nullable=False),
    sa.Column('category_match', sa.Boolean(), nullable=False),
    sa.Column('package_match', sa.Boolean(), nullable=False),
    sa.Column('manufacturer_match', sa.Boolean(), nullable=False),
    sa.Column('lifecycle_score', sa.Float(), nullable=False),
    sa.Column('availability_score', sa.Float(), nullable=False),
    sa.Column('reasons', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alternative_component_id'], ['components.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_component_id'], ['components.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alternative_records_alternative_component_id'), 'alternative_records', ['alternative_component_id'], unique=False)
    op.create_index(op.f('ix_alternative_records_source_component_id'), 'alternative_records', ['source_component_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alternative_records_source_component_id'), table_name='alternative_records')
    op.drop_index(op.f('ix_alternative_records_alternative_component_id'), table_name='alternative_records')
    op.drop_table('alternative_records')
    # ### end Alembic commands ###