"""create bom components

Revision ID: 28f3c02fcae5
Revises: 0be8422a0593
Create Date: 2026-08-12 10:01:25.220157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28f3c02fcae5'
down_revision: Union[str, Sequence[str], None] = '0be8422a0593'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bom_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bom_id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reference_designators', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['bom_id'], ['boms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bom_id', 'component_id', name='uq_bom_component')
    )
    op.create_index(op.f('ix_bom_components_bom_id'), 'bom_components', ['bom_id'], unique=False)
    op.create_index(op.f('ix_bom_components_component_id'), 'bom_components', ['component_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bom_components_component_id'), table_name='bom_components')
    op.drop_index(op.f('ix_bom_components_bom_id'), table_name='bom_components')
    op.drop_table('bom_components')
    # ### end Alembic commands ###