"""create lifecycle records

Revision ID: 5468fac27d39
Revises: f17c38ef036f
Create Date: 2026-08-12 10:09:48.532934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5468fac27d39'
down_revision: Union[str, Sequence[str], None] = 'f17c38ef036f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lifecycle_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('eol_date', sa.Date(), nullable=True),
    sa.Column('last_buy_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lifecycle_records_component_id'), 'lifecycle_records', ['component_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lifecycle_records_component_id'), table_name='lifecycle_records')
    op.drop_table('lifecycle_records')
    # ### end Alembic commands ###