"""create bom risk records

Revision ID: eb3809484a6f
Revises: 6ffd421d6fbf
Create Date: 2026-08-12 17:04:34.425053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb3809484a6f'
down_revision: Union[str, Sequence[str], None] = '6ffd421d6fbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bom_risk_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bom_id', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('component_count', sa.Integer(), nullable=False),
    sa.Column('high_risk_count', sa.Integer(), nullable=False),
    sa.Column('critical_count', sa.Integer(), nullable=False),
    sa.Column('lifecycle_risk_count', sa.Integer(), nullable=False),
    sa.Column('availability_risk_count', sa.Integer(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bom_id'], ['boms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bom_risk_records_bom_id'), 'bom_risk_records', ['bom_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bom_risk_records_bom_id'), table_name='bom_risk_records')
    op.drop_table('bom_risk_records')
    # ### end Alembic commands ###