"""create ingestion records

Revision ID: f17c38ef036f
Revises: 28f3c02fcae5
Create Date: 2026-08-12 10:04:59.121330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f17c38ef036f'
down_revision: Union[str, Sequence[str], None] = '28f3c02fcae5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bom_id', sa.Integer(), nullable=False),
    sa.Column('source_file', sa.String(length=500), nullable=False),
    sa.Column('source_format', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bom_id'], ['boms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_records_bom_id'), 'ingestion_records', ['bom_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingestion_records_bom_id'), table_name='ingestion_records')
    op.drop_table('ingestion_records')
    # ### end Alembic commands ###